name: CD

on:
  workflow_call:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: diyws
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/diyws.tar
          docker image ls -a

      - name: Sign in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u renatodellosso --password-stdin

      - name: Push to GHCR
        run: docker push ghcr.io/renatodellosso/diyws:latest
