name: CD

on:
  workflow_call:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/renatodellosso/diyws:latest
          outputs: type=oci,dest=/tmp/diyws.tar
          file: ./Dockerfile.prod
          platforms: amd64,arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

      - name: Sign in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u renatodellosso --password-stdin

      - name: Push to GHCR
        run: docker push ghcr.io/renatodellosso/diyws:latest
